# Generated by Django 6.0.5 on 2026-06-20 04:35

import api.fields
import django.contrib.postgres.indexes
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(db_index=True, max_length=255)),
                ('contact_name', models.CharField(max_length=255)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('blocked', 'Blocked')], default='active', max_length=16)),
                ('details', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['company_name', 'contact_name'],
            },
        ),
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('status', models.CharField(choices=[('forming', 'Forming'), ('open', 'Open'), ('closed', 'Closed')], default='forming', max_length=16)),
                ('details', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address_normalized', models.CharField(db_index=True, max_length=512, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(db_index=True, max_length=120)),
                ('state', models.CharField(db_index=True, max_length=2)),
                ('zip', models.CharField(max_length=20)),
                ('property_type', models.CharField(choices=[('multifamily', 'Multifamily'), ('office', 'Office'), ('retail', 'Retail'), ('industrial', 'Industrial'), ('hotel', 'Hotel'), ('self_storage', 'Self storage'), ('land', 'Land'), ('mixed_use', 'Mixed use'), ('data_center', 'Data center'), ('condo', 'Condo'), ('master_planned_residential', 'Master planned residential'), ('other', 'Other')], max_length=40)),
                ('msa', models.CharField(blank=True, db_index=True, max_length=160)),
                ('details', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name_plural': 'properties',
                'ordering': ['address_normalized'],
            },
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_name', models.CharField(db_index=True, max_length=255)),
                ('entity_type', models.CharField(choices=[('llc', 'LLC'), ('lp', 'LP'), ('corp', 'Corporation'), ('trust', 'Trust'), ('individual', 'Individual')], max_length=24)),
                ('primary_contact_name', models.CharField(max_length=255)),
                ('primary_contact_email', models.EmailField(db_index=True, max_length=254)),
                ('primary_contact_phone', models.CharField(blank=True, max_length=40)),
                ('relationship_rating', models.CharField(choices=[('new', 'New'), ('developing', 'Developing'), ('established', 'Established'), ('strategic', 'Strategic')], default='new', max_length=24)),
                ('ein', api.fields.EncryptedTextField(blank=True)),
                ('guarantor_net_worth', api.fields.EncryptedTextField(blank=True)),
                ('guarantor_liquidity', api.fields.EncryptedTextField(blank=True)),
                ('guarantor_credit_score', api.fields.EncryptedTextField(blank=True)),
                ('details', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['entity_name'],
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('investment_type', models.CharField(choices=[('whole_loan_bridge', 'Whole loan bridge'), ('whole_loan_permanent', 'Whole loan permanent'), ('mezzanine', 'Mezzanine'), ('preferred_equity', 'Preferred equity'), ('co_gp_equity', 'Co-GP equity'), ('lp_equity', 'LP equity')], max_length=32)),
                ('pipeline_status', models.CharField(choices=[('sourced', 'Sourced'), ('screening', 'Screening'), ('quoting', 'Quoting'), ('negotiating', 'Negotiating'), ('signed', 'Signed'), ('closing', 'Closing'), ('closed', 'Closed'), ('servicing', 'Servicing'), ('on_hold', 'On hold'), ('dead', 'Dead'), ('exited', 'Exited')], db_index=True, default='sourced', max_length=24)),
                ('syndication_status', models.CharField(choices=[('not_started', 'Not started'), ('raising', 'Raising'), ('fully_subscribed', 'Fully subscribed'), ('closed', 'Closed')], db_index=True, default='not_started', max_length=24)),
                ('paused_from_status', models.CharField(blank=True, choices=[('sourced', 'Sourced'), ('screening', 'Screening'), ('quoting', 'Quoting'), ('negotiating', 'Negotiating'), ('signed', 'Signed'), ('closing', 'Closing'), ('closed', 'Closed'), ('servicing', 'Servicing'), ('on_hold', 'On hold'), ('dead', 'Dead'), ('exited', 'Exited')], max_length=24, null=True)),
                ('source_channel', models.CharField(choices=[('broker', 'Broker'), ('direct', 'Direct'), ('referral', 'Referral'), ('repeat_sponsor', 'Repeat sponsor'), ('internal_prospecting', 'Internal prospecting')], db_index=True, max_length=32)),
                ('source_date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('requested_amount', models.DecimalField(decimal_places=2, max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_analyst', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_deals', to=settings.AUTH_USER_MODEL)),
                ('broker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deals', to='api.broker')),
                ('fund', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='api.fund')),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deals', to='api.sponsor')),
            ],
            options={
                'ordering': ['-source_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('status_change', 'Status change'), ('field_updated', 'Field updated'), ('document_upload', 'Document upload'), ('note_added', 'Note added'), ('sensitive_field_read', 'Sensitive field read')], db_index=True, max_length=40)),
                ('performed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('description', models.TextField()),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('reason', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='api.deal')),
            ],
            options={
                'ordering': ['-performed_at', '-id'],
                'indexes': [models.Index(fields=['deal', '-performed_at'], name='api_activit_deal_id_49d718_idx'), models.Index(fields=['action_type', '-performed_at'], name='api_activit_action__0ea497_idx'), django.contrib.postgres.indexes.GinIndex(fields=['metadata'], name='api_activity_metadata_gin')],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('offering_memo', 'Offering memo'), ('financials', 'Financials'), ('rent_roll', 'Rent roll'), ('appraisal', 'Appraisal'), ('environmental', 'Environmental'), ('title', 'Title'), ('insurance', 'Insurance'), ('legal', 'Legal'), ('entity_docs', 'Entity docs'), ('construction', 'Construction'), ('investor_docs', 'Investor docs'), ('correspondence', 'Correspondence'), ('closing_docs', 'Closing docs'), ('servicing', 'Servicing'), ('other', 'Other')], max_length=32)),
                ('version', models.PositiveIntegerField(default=1)),
                ('file_url', models.CharField(max_length=1024)),
                ('file_type', models.CharField(max_length=24)),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('is_executed', models.BooleanField(default=False)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('visibility_roles', models.JSONField(blank=True, default=list)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='api.deal')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['deal', 'category', '-version'],
                'indexes': [models.Index(fields=['deal', 'category'], name='api_documen_deal_id_0282ad_idx'), models.Index(fields=['expiry_date'], name='api_documen_expiry__861eb6_idx'), django.contrib.postgres.indexes.GinIndex(fields=['visibility_roles'], name='api_document_roles_gin')],
            },
        ),
        migrations.CreateModel(
            name='DealProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal_properties', to='api.deal')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal_properties', to='api.property')),
            ],
            options={
                'ordering': ['-is_primary', 'property__address_normalized'],
                'constraints': [models.UniqueConstraint(fields=('deal', 'property'), name='unique_deal_property'), models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('deal',), name='unique_primary_property_per_deal')],
            },
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['pipeline_status', 'syndication_status'], name='api_deal_pipelin_2254d1_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['assigned_analyst', 'pipeline_status'], name='api_deal_assigne_044dfd_idx'),
        ),
        migrations.AddConstraint(
            model_name='deal',
            constraint=models.CheckConstraint(condition=models.Q(('requested_amount__gt', 0)), name='deal_requested_amount_positive'),
        ),
    ]
