# Generated by Django 6.0.5 on 2026-07-09

import uuid
from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_stage_history'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreeningAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField()),
                (
                    'status',
                    models.CharField(
                        choices=[('draft', 'Draft'), ('finalized', 'Finalized')],
                        db_index=True,
                        default='draft',
                        max_length=16,
                    ),
                ),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                (
                    'decision',
                    models.CharField(
                        blank=True,
                        choices=[('advance', 'Advance'), ('refer', 'Refer'), ('decline', 'Decline')],
                        default='',
                        max_length=16,
                    ),
                ),
                ('notes', models.TextField(blank=True)),
                (
                    'loan_amount',
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=16,
                        null=True,
                        validators=[MinValueValidator(Decimal('0'))],
                    ),
                ),
                (
                    'as_is_value',
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=16,
                        null=True,
                        validators=[MinValueValidator(Decimal('0'))],
                    ),
                ),
                (
                    'stabilized_value',
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=16,
                        null=True,
                        validators=[MinValueValidator(Decimal('0'))],
                    ),
                ),
                (
                    'project_cost',
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=16,
                        null=True,
                        validators=[MinValueValidator(Decimal('0'))],
                    ),
                ),
                (
                    'noi',
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=16,
                        null=True,
                        validators=[MinValueValidator(Decimal('0'))],
                    ),
                ),
                (
                    'annual_debt_service',
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=16,
                        null=True,
                        validators=[MinValueValidator(Decimal('0'))],
                    ),
                ),
                (
                    'occupancy',
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text='Percent occupied, from 0 through 100.',
                        max_digits=5,
                        null=True,
                        validators=[MinValueValidator(Decimal('0')), MaxValueValidator(Decimal('100'))],
                    ),
                ),
                (
                    'proposed_rate',
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text='Annual proposed interest rate expressed as a percentage.',
                        max_digits=7,
                        null=True,
                        validators=[MinValueValidator(Decimal('0')), MaxValueValidator(Decimal('100'))],
                    ),
                ),
                (
                    'proposed_term_months',
                    models.PositiveIntegerField(blank=True, null=True, validators=[MinValueValidator(1)]),
                ),
                (
                    'max_ltv',
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal('0.7500'),
                        max_digits=8,
                        validators=[MinValueValidator(Decimal('0')), MaxValueValidator(Decimal('1'))],
                    ),
                ),
                (
                    'max_ltc',
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal('0.8500'),
                        max_digits=8,
                        validators=[MinValueValidator(Decimal('0')), MaxValueValidator(Decimal('1'))],
                    ),
                ),
                (
                    'min_dscr',
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal('1.2000'),
                        max_digits=8,
                        validators=[MinValueValidator(Decimal('0'))],
                    ),
                ),
                (
                    'min_debt_yield',
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal('0.0800'),
                        max_digits=8,
                        validators=[MinValueValidator(Decimal('0')), MaxValueValidator(Decimal('1'))],
                    ),
                ),
                ('ltv_as_is', models.DecimalField(blank=True, decimal_places=4, editable=False, max_digits=12, null=True)),
                ('ltv_stabilized', models.DecimalField(blank=True, decimal_places=4, editable=False, max_digits=12, null=True)),
                ('ltc', models.DecimalField(blank=True, decimal_places=4, editable=False, max_digits=12, null=True)),
                ('dscr', models.DecimalField(blank=True, decimal_places=4, editable=False, max_digits=12, null=True)),
                ('debt_yield', models.DecimalField(blank=True, decimal_places=4, editable=False, max_digits=12, null=True)),
                (
                    'quick_score',
                    models.PositiveSmallIntegerField(
                        default=0,
                        editable=False,
                        validators=[MinValueValidator(0), MaxValueValidator(100)],
                    ),
                ),
                ('equity_summary', models.TextField(blank=True)),
                (
                    'equity_target_irr',
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text='Target IRR expressed as a percentage.',
                        max_digits=7,
                        null=True,
                        validators=[MinValueValidator(Decimal('0')), MaxValueValidator(Decimal('100'))],
                    ),
                ),
                (
                    'equity_target_multiple',
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=8,
                        null=True,
                        validators=[MinValueValidator(Decimal('0'))],
                    ),
                ),
                (
                    'equity_target_hold_months',
                    models.PositiveIntegerField(blank=True, null=True, validators=[MinValueValidator(1)]),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'deal',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='screening_assessments',
                        to='api.deal',
                    ),
                ),
                (
                    'reviewer',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='reviewed_screening_assessments',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'ordering': ['deal', '-version'],
                'indexes': [
                    models.Index(fields=['deal', '-version'], name='screening_deal_version_idx'),
                    models.Index(fields=['deal', 'status'], name='screening_deal_status_idx'),
                ],
                'constraints': [
                    models.UniqueConstraint(fields=['deal', 'version'], name='screening_assessment_deal_version_unique'),
                    models.UniqueConstraint(condition=models.Q(status='draft'), fields=['deal'], name='screening_assessment_one_draft_per_deal'),
                    models.CheckConstraint(condition=models.Q(version__gt=0), name='screening_assessment_version_positive'),
                    models.CheckConstraint(
                        condition=models.Q(quick_score__gte=0, quick_score__lte=100),
                        name='screening_assessment_score_range',
                    ),
                    models.CheckConstraint(
                        condition=(
                            models.Q(occupancy__isnull=True)
                            | models.Q(occupancy__gte=0, occupancy__lte=100)
                        ),
                        name='screening_assessment_occupancy_range',
                    ),
                    models.CheckConstraint(
                        condition=(
                            models.Q(status='draft', reviewer__isnull=True, finalized_at__isnull=True)
                            | (
                                models.Q(
                                    status='finalized',
                                    reviewer__isnull=False,
                                    finalized_at__isnull=False,
                                )
                                & ~models.Q(decision='')
                            )
                        ),
                        name='screening_assessment_finalization_state',
                    ),
                ],
            },
        ),
    ]
