# Generated by Django 6.0.5 on 2026-07-11 06:13

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='estimated_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='deal',
            name='profile',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='deal',
            name='purpose',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='deal',
            name='renovation_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='property',
            name='county',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddField(
            model_name='property',
            name='rentable_square_feet',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='subtype',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='property',
            name='units',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='year_built',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1700), django.core.validators.MaxValueValidator(2200)]),
        ),
        migrations.AddField(
            model_name='property',
            name='year_renovated',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1700), django.core.validators.MaxValueValidator(2200)]),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='bankruptcy_history',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='completed_projects',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='years_experience',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(200)]),
        ),
        migrations.AddConstraint(
            model_name='deal',
            constraint=models.CheckConstraint(condition=models.Q(('estimated_value__isnull', True), ('estimated_value__gte', 0), _connector='OR'), name='deal_estimated_value_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='deal',
            constraint=models.CheckConstraint(condition=models.Q(('renovation_budget__isnull', True), ('renovation_budget__gte', 0), _connector='OR'), name='deal_renovation_budget_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='property',
            constraint=models.CheckConstraint(condition=models.Q(('year_built__isnull', True), models.Q(('year_built__gte', 1700), ('year_built__lte', 2200)), _connector='OR'), name='property_year_built_range'),
        ),
        migrations.AddConstraint(
            model_name='property',
            constraint=models.CheckConstraint(condition=models.Q(('year_renovated__isnull', True), models.Q(('year_renovated__gte', 1700), ('year_renovated__lte', 2200)), _connector='OR'), name='property_year_renovated_range'),
        ),
        migrations.AddConstraint(
            model_name='property',
            constraint=models.CheckConstraint(condition=models.Q(('year_built__isnull', True), ('year_renovated__isnull', True), ('year_renovated__gte', models.F('year_built')), _connector='OR'), name='property_renovation_after_built'),
        ),
        migrations.AddConstraint(
            model_name='sponsor',
            constraint=models.CheckConstraint(condition=models.Q(('years_experience__isnull', True), ('years_experience__lte', 200), _connector='OR'), name='sponsor_years_experience_range'),
        ),
    ]
