# Generated by Django 6.0.5 on 2026-07-14 15:40

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_deal_description_deal_estimated_value_deal_profile_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('countered', 'Countered'), ('executed', 'Executed'), ('expired', 'Expired'), ('withdrawn', 'Withdrawn')], db_index=True, default='draft', max_length=16)),
                ('is_counter', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('loan_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('rate_type', models.CharField(blank=True, choices=[('fixed', 'Fixed'), ('floating', 'Floating'), ('hybrid', 'Hybrid')], default='', max_length=16)),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=4, help_text='Annual interest rate in percentage points.', max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('index_name', models.CharField(blank=True, max_length=64)),
                ('spread', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('rate_floor', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('term_months', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('amortization_type', models.CharField(blank=True, choices=[('interest_only', 'Interest only'), ('partial_amort', 'Partial amort'), ('full_amort', 'Full amort')], default='', max_length=16)),
                ('amortization_months', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('origination_fee_pct', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('origination_fee_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('exit_fee_pct', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('extension_options', models.JSONField(blank=True, default=list)),
                ('prepayment_terms', models.TextField(blank=True)),
                ('recourse_type', models.CharField(blank=True, choices=[('full', 'Full'), ('limited', 'Limited'), ('non_recourse', 'Non-recourse with carveouts')], default='', max_length=16)),
                ('recourse_carveouts', models.TextField(blank=True)),
                ('interest_reserve_months', models.PositiveIntegerField(blank=True, null=True)),
                ('interest_reserve_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('holdback_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('initial_funding_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('good_faith_deposit', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('min_dscr', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('max_ltv', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))])),
                ('min_debt_yield', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))])),
                ('equity_commitment', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('ownership_pct', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('preferred_return_pct', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('equity_summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attachments', models.ManyToManyField(blank=True, related_name='quotes', to='api.document')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_quotes', to=settings.AUTH_USER_MODEL)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='api.deal')),
            ],
            options={
                'ordering': ['deal', '-version'],
                'indexes': [models.Index(fields=['deal', 'status'], name='quote_deal_status_idx'), models.Index(fields=['deal', '-version'], name='quote_deal_version_idx')],
                'constraints': [models.UniqueConstraint(fields=('deal', 'version'), name='quote_deal_version_unique'), models.UniqueConstraint(condition=models.Q(('status', 'draft')), fields=('deal',), name='quote_one_draft_per_deal'), models.CheckConstraint(condition=models.Q(('version__gt', 0)), name='quote_version_positive'), models.CheckConstraint(condition=models.Q(models.Q(('sent_at__isnull', True), ('signed_at__isnull', True), ('status', 'draft'), ('withdrawn_at__isnull', True)), models.Q(('sent_at__isnull', False), ('signed_at__isnull', True), ('status__in', ['sent', 'countered', 'expired']), ('withdrawn_at__isnull', True)), models.Q(('sent_at__isnull', False), ('signed_at__isnull', False), ('status', 'executed'), ('withdrawn_at__isnull', True)), models.Q(('signed_at__isnull', True), ('status', 'withdrawn'), ('withdrawn_at__isnull', False)), _connector='OR'), name='quote_lifecycle_timestamps')],
            },
        ),
    ]
