# Generated by Django 6.0.5 on 2026-07-15 05:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def seed_dd_templates(apps, schema_editor):
    DDTemplate = apps.get_model('api', 'DDTemplate')
    DDTemplateItem = apps.get_model('api', 'DDTemplateItem')

    templates = {
        'debt_acquisition': {
            'name': 'Debt acquisition',
            'description': 'Standard acquisition financing closing checklist.',
            'items': [
                ('dd', 1, 'Title commitment / proforma policy', '', 14),
                ('dd', 2, 'Survey', '', 14),
                ('dd', 3, 'Environmental (Phase I)', '', 21),
                ('dd', 4, 'Appraisal', '', 21),
                ('dd', 5, 'Insurance binder', '', 7),
                ('dd', 6, 'Entity / authority docs', '', 10),
                ('dd', 7, 'Loan documents drafted', '', 5),
                ('cp', 1, 'Executed loan documents received', '', 0),
                ('cp', 2, 'Title clear to close', '', 0),
            ],
        },
        'bridge_loan': {
            'name': 'Bridge loan',
            'description': 'Shorter bridge closing checklist.',
            'items': [
                ('dd', 1, 'Title commitment', '', 10),
                ('dd', 2, 'Insurance binder', '', 7),
                ('dd', 3, 'Entity / authority docs', '', 7),
                ('dd', 4, 'Loan documents drafted', '', 5),
                ('cp', 1, 'Executed loan documents received', '', 0),
                ('cp', 2, 'Title clear to close', '', 0),
            ],
        },
        'equity_investment': {
            'name': 'Equity investment',
            'description': 'General equity / hybrid investment closing checklist.',
            'items': [
                ('dd', 1, 'Entity docs', '', 14),
                ('dd', 2, 'Operating agreement / subscription docs', '', 14),
                ('dd', 3, 'Insurance (as applicable)', '', 7),
                ('dd', 4, 'Third-party reports (as applicable)', '', 21),
                ('cp', 1, 'Executed investment documents received', '', 0),
                ('cp', 2, 'KYC/AML package complete', '', 0),
            ],
        },
    }

    for key, payload in templates.items():
        template, _ = DDTemplate.objects.get_or_create(
            key=key,
            defaults={
                'name': payload['name'],
                'description': payload['description'],
                'is_active': True,
            },
        )
        for kind, sort_order, title, description, days in payload['items']:
            DDTemplateItem.objects.get_or_create(
                template=template,
                kind=kind,
                sort_order=sort_order,
                defaults={
                    'title': title,
                    'description': description,
                    'default_days_before_target_close': days,
                },
            )


def unseed_dd_templates(apps, schema_editor):
    DDTemplate = apps.get_model('api', 'DDTemplate')
    DDTemplate.objects.filter(
        key__in=['debt_acquisition', 'bridge_loan', 'equity_investment'],
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_quote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DDTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action_type',
            field=models.CharField(choices=[('status_change', 'Status change'), ('field_updated', 'Field updated'), ('document_upload', 'Document upload'), ('note_added', 'Note added'), ('sensitive_field_read', 'Sensitive field read'), ('closing_generated', 'Closing checklist generated'), ('closing_regenerated', 'Closing checklist regenerated'), ('closing_superseded', 'Closing checklist superseded'), ('closing_item_updated', 'Closing item updated'), ('closing_document_linked', 'Closing document linked'), ('closing_package_updated', 'Closing package updated')], db_index=True, max_length=40),
        ),
        migrations.CreateModel(
            name='ClosingPackage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_close_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deal', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='closing_package', to='api.deal')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ClosingChecklistGeneration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField()),
                ('template_key', models.CharField(max_length=64)),
                ('template_name', models.CharField(max_length=255)),
                ('is_current', models.BooleanField(db_index=True, default=True)),
                ('generated_at', models.DateTimeField()),
                ('superseded_at', models.DateTimeField(blank=True, null=True)),
                ('supersede_reason', models.TextField(blank=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_closing_checklists', to=settings.AUTH_USER_MODEL)),
                ('superseded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_closing_checklists', to=settings.AUTH_USER_MODEL)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generations', to='api.closingpackage')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generations', to='api.ddtemplate')),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='DDTemplateItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sort_order', models.PositiveIntegerField()),
                ('kind', models.CharField(choices=[('dd', 'Due diligence'), ('cp', 'Condition precedent')], max_length=8)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('default_days_before_target_close', models.IntegerField(blank=True, null=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.ddtemplate')),
            ],
            options={
                'ordering': ['kind', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='DDChecklistItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sort_order', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In progress'), ('complete', 'Complete'), ('waived', 'Waived')], db_index=True, default='pending', max_length=16)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('waiver_reason', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('waived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_dd_items', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_dd_items', to=settings.AUTH_USER_MODEL)),
                ('documents', models.ManyToManyField(blank=True, related_name='dd_checklist_items', to='api.document')),
                ('generation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dd_items', to='api.closingchecklistgeneration')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_dd_items', to=settings.AUTH_USER_MODEL)),
                ('waived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waived_dd_items', to=settings.AUTH_USER_MODEL)),
                ('source_template_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dd_items', to='api.ddtemplateitem')),
            ],
            options={
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConditionPrecedent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sort_order', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('satisfied', 'Satisfied'), ('waived', 'Waived')], db_index=True, default='open', max_length=16)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('waiver_reason', models.TextField(blank=True)),
                ('satisfied_at', models.DateTimeField(blank=True, null=True)),
                ('waived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_conditions_precedent', to=settings.AUTH_USER_MODEL)),
                ('documents', models.ManyToManyField(blank=True, related_name='condition_precedents', to='api.document')),
                ('generation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions_precedent', to='api.closingchecklistgeneration')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_conditions_precedent', to=settings.AUTH_USER_MODEL)),
                ('satisfied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='satisfied_conditions_precedent', to=settings.AUTH_USER_MODEL)),
                ('waived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waived_conditions_precedent', to=settings.AUTH_USER_MODEL)),
                ('source_template_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='condition_precedents', to='api.ddtemplateitem')),
            ],
            options={
                'verbose_name_plural': 'conditions precedent',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='closingchecklistgeneration',
            constraint=models.UniqueConstraint(fields=('package', 'version'), name='unique_closing_generation_version'),
        ),
        migrations.AddConstraint(
            model_name='closingchecklistgeneration',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('package',), name='unique_current_closing_generation'),
        ),
        migrations.AddConstraint(
            model_name='closingchecklistgeneration',
            constraint=models.CheckConstraint(condition=models.Q(('version__gt', 0)), name='closing_generation_version_positive'),
        ),
        migrations.AddConstraint(
            model_name='closingchecklistgeneration',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_current', True), ('supersede_reason', ''), ('superseded_at__isnull', True)), models.Q(('is_current', False), ('superseded_at__isnull', False)), _connector='OR'), name='closing_generation_current_or_superseded'),
        ),
        migrations.AddConstraint(
            model_name='closingchecklistgeneration',
            constraint=models.CheckConstraint(condition=models.Q(('superseded_at__isnull', True), ('superseded_at__gte', models.F('generated_at')), _connector='OR'), name='closing_generation_superseded_after_generated'),
        ),
        migrations.AddConstraint(
            model_name='ddtemplateitem',
            constraint=models.UniqueConstraint(fields=('template', 'kind', 'sort_order'), name='unique_dd_template_item_sort'),
        ),
        migrations.AddConstraint(
            model_name='ddchecklistitem',
            constraint=models.UniqueConstraint(fields=('generation', 'sort_order'), name='unique_dd_item_sort'),
        ),
        migrations.AddConstraint(
            model_name='ddchecklistitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'complete'), ('completed_at__isnull', False), ('waived_at__isnull', True), ('waiver_reason', '')), models.Q(('status', 'waived'), ('waived_at__isnull', False), models.Q(('waiver_reason', ''), _negated=True), ('completed_at__isnull', True)), models.Q(('status__in', ['pending', 'in_progress']), ('completed_at__isnull', True), ('waived_at__isnull', True), ('waiver_reason', '')), _connector='OR'), name='dd_item_status_timestamps'),
        ),
        migrations.AddConstraint(
            model_name='conditionprecedent',
            constraint=models.UniqueConstraint(fields=('generation', 'sort_order'), name='unique_cp_item_sort'),
        ),
        migrations.AddConstraint(
            model_name='conditionprecedent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'satisfied'), ('satisfied_at__isnull', False), ('waived_at__isnull', True), ('waiver_reason', '')), models.Q(('status', 'waived'), ('waived_at__isnull', False), models.Q(('waiver_reason', ''), _negated=True), ('satisfied_at__isnull', True)), models.Q(('status', 'open'), ('satisfied_at__isnull', True), ('waived_at__isnull', True), ('waiver_reason', '')), _connector='OR'), name='cp_item_status_timestamps'),
        ),
        migrations.RunPython(seed_dd_templates, unseed_dd_templates),
    ]

