# Generated by Django 6.0.5 on 2026-07-15 13:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_closing_dd'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='closingchecklistgeneration',
            name='closing_generation_current_or_superseded',
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action_type',
            field=models.CharField(choices=[('status_change', 'Status change'), ('field_updated', 'Field updated'), ('document_upload', 'Document upload'), ('note_added', 'Note added'), ('sensitive_field_read', 'Sensitive field read'), ('closing_generated', 'Closing checklist generated'), ('closing_regenerated', 'Closing checklist regenerated'), ('closing_superseded', 'Closing checklist superseded'), ('closing_item_updated', 'Closing item updated'), ('closing_document_linked', 'Closing document linked'), ('closing_document_detached', 'Closing document detached'), ('closing_package_updated', 'Closing package updated')], db_index=True, max_length=40),
        ),
        migrations.AddConstraint(
            model_name='closingchecklistgeneration',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_current', True), ('supersede_reason', ''), ('superseded_at__isnull', True), ('superseded_by__isnull', True)), models.Q(('is_current', False), ('superseded_at__isnull', False)), _connector='OR'), name='closing_generation_current_or_superseded'),
        ),
    ]
