# Generated by Django 6.0.5 on 2026-07-15 23:57

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_closing_review_fixes'),
    ]

    operations = [
        migrations.AddField(
            model_name='broker',
            name='commission_type',
            field=models.CharField(blank=True, choices=[('percent_of_loan', 'Percent of loan'), ('flat_fee', 'Flat fee'), ('percent_of_equity', 'Percent of equity'), ('referral_fee', 'Referral fee')], max_length=32),
        ),
        migrations.AddField(
            model_name='broker',
            name='default_commission_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='broker',
            name='geographic_focus',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='broker',
            name='preferred_deal_types',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='closingpackage',
            name='actual_close_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='closingpackage',
            name='appraised_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='closingpackage',
            name='closing_attorney',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='closingpackage',
            name='closing_costs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='closingpackage',
            name='final_loan_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddField(
            model_name='closingpackage',
            name='funds_wired_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddField(
            model_name='closingpackage',
            name='funds_wired_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='closingpackage',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='closingpackage',
            name='sources_and_uses_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='closingpackage',
            name='title_company',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='deal',
            name='deposit_account_label',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='deal',
            name='deposit_received_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='deposit_refund_conditions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='deposit_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('received', 'Received'), ('applied_to_closing', 'Applied to closing'), ('refunded', 'Refunded')], max_length=24),
        ),
        migrations.AddField(
            model_name='deal',
            name='exclusivity_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='exclusivity_granted',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='key_negotiation_changes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='property',
            name='environmental_status',
            field=models.CharField(blank=True, choices=[('none', 'None identified'), ('phase_1_clean', 'Phase I clean'), ('phase_1_rec', 'Phase I REC'), ('phase_2_required', 'Phase II required'), ('phase_2_clean', 'Phase II clean'), ('remediation', 'Remediation required')], max_length=32),
        ),
        migrations.AddField(
            model_name='property',
            name='flood_zone',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='property',
            name='lot_size_acres',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='property',
            name='number_of_buildings',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='number_of_stories',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='parking_spaces',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='zoning_designation',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='screeningassessment',
            name='condition_rating',
            field=models.CharField(blank=True, choices=[('poor', 'Poor'), ('fair', 'Fair'), ('good', 'Good'), ('excellent', 'Excellent')], default='', max_length=16),
        ),
        migrations.AddField(
            model_name='screeningassessment',
            name='current_average_rent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='screeningassessment',
            name='exit_cap_rate',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Expected exit capitalization rate expressed as a percentage.', max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
        migrations.AddField(
            model_name='screeningassessment',
            name='exit_strategy',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='screeningassessment',
            name='market_rent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='screeningassessment',
            name='stabilized_noi',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='screeningassessment',
            name='unit_mix',
            field=models.TextField(blank=True, help_text='Concise manual description of unit, tenant, or collateral mix.'),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='assets_under_management',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='business_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='connection_source',
            field=models.CharField(blank=True, choices=[('broker_referral', 'Broker referral'), ('direct', 'Direct'), ('repeat', 'Repeat relationship'), ('marketing', 'Marketing'), ('conference', 'Conference')], max_length=32),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='total_sf_managed',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='total_units_owned',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='track_record',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action_type',
            field=models.CharField(choices=[('status_change', 'Status change'), ('field_updated', 'Field updated'), ('document_upload', 'Document upload'), ('note_added', 'Note added'), ('sensitive_field_read', 'Sensitive field read'), ('closing_generated', 'Closing checklist generated'), ('closing_regenerated', 'Closing checklist regenerated'), ('closing_superseded', 'Closing checklist superseded'), ('closing_item_updated', 'Closing item updated'), ('closing_document_linked', 'Closing document linked'), ('closing_document_detached', 'Closing document detached'), ('closing_package_updated', 'Closing package updated'), ('quote_created', 'Quote created'), ('quote_updated', 'Quote updated'), ('quote_sent', 'Quote sent'), ('quote_countered', 'Quote countered'), ('quote_executed', 'Quote executed'), ('quote_expired', 'Quote expired'), ('quote_withdrawn', 'Quote withdrawn'), ('quote_attachments_updated', 'Quote attachments updated')], db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='deal',
            name='profile',
            field=models.CharField(blank=True, choices=[('value_add', 'Value-add'), ('construction', 'Construction'), ('stabilized', 'Stabilized')], max_length=32),
        ),
        migrations.AlterField(
            model_name='deal',
            name='purpose',
            field=models.CharField(blank=True, choices=[('acquisition', 'Acquisition'), ('refinance', 'Refinance'), ('construction', 'Construction'), ('recapitalization', 'Recapitalization')], max_length=32),
        ),
    ]
