# Generated by Django 6.0.5 on 2026-07-16 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_broker_commission_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='syndication_status',
            field=models.CharField(choices=[('not_started', 'Not started'), ('raising', 'Raising'), ('fully_subscribed', 'Fully subscribed'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], db_index=True, default='not_started', max_length=24),
        ),
    ]
