# Generated by Django 6.0.5 on 2026-07-16 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_document_options_alter_activitylog_action_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action_type',
            field=models.CharField(choices=[('status_change', 'Status change'), ('field_updated', 'Field updated'), ('document_upload_started', 'Document upload started'), ('document_upload', 'Document upload'), ('document_upload_abandoned', 'Document upload abandoned'), ('note_added', 'Note added'), ('note_updated', 'Note updated'), ('note_deleted', 'Note deleted'), ('sensitive_field_read', 'Sensitive field read'), ('closing_generated', 'Closing checklist generated'), ('closing_regenerated', 'Closing checklist regenerated'), ('closing_superseded', 'Closing checklist superseded'), ('closing_item_updated', 'Closing item updated'), ('closing_document_linked', 'Closing document linked'), ('closing_document_detached', 'Closing document detached'), ('closing_package_updated', 'Closing package updated'), ('quote_created', 'Quote created'), ('quote_updated', 'Quote updated'), ('quote_sent', 'Quote sent'), ('quote_countered', 'Quote countered'), ('quote_executed', 'Quote executed'), ('quote_expired', 'Quote expired'), ('quote_withdrawn', 'Quote withdrawn'), ('quote_attachments_updated', 'Quote attachments updated')], db_index=True, max_length=40),
        ),
    ]
