# Generated by Django 6.0.5 on 2026-07-16 06:46

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_activitylog_action_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action_type',
            field=models.CharField(choices=[('status_change', 'Status change'), ('field_updated', 'Field updated'), ('document_upload_started', 'Document upload started'), ('document_upload', 'Document upload'), ('document_upload_abandoned', 'Document upload abandoned'), ('document_delete_pending', 'Document deletion pending'), ('document_deleted', 'Document deleted'), ('note_added', 'Note added'), ('note_updated', 'Note updated'), ('note_deleted', 'Note deleted'), ('sensitive_field_read', 'Sensitive field read'), ('closing_generated', 'Closing checklist generated'), ('closing_regenerated', 'Closing checklist regenerated'), ('closing_superseded', 'Closing checklist superseded'), ('closing_item_updated', 'Closing item updated'), ('closing_document_linked', 'Closing document linked'), ('closing_document_detached', 'Closing document detached'), ('closing_package_updated', 'Closing package updated'), ('quote_created', 'Quote created'), ('quote_updated', 'Quote updated'), ('quote_sent', 'Quote sent'), ('quote_countered', 'Quote countered'), ('quote_executed', 'Quote executed'), ('quote_expired', 'Quote expired'), ('quote_withdrawn', 'Quote withdrawn'), ('quote_attachments_updated', 'Quote attachments updated'), ('screening_created', 'Screening created'), ('screening_updated', 'Screening updated'), ('screening_finalized', 'Screening finalized'), ('deal_contact_added', 'Deal contact added'), ('deal_contact_updated', 'Deal contact updated'), ('deal_contact_deleted', 'Deal contact deleted')], db_index=True, max_length=40),
        ),
        migrations.CreateModel(
            name='DocumentBlobDeletion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_id', models.UUIDField()),
                ('document_name', models.CharField(max_length=255)),
                ('storage_key', models.CharField(max_length=1024, unique=True)),
                ('reason', models.CharField(choices=[('user_delete', 'User deleted document'), ('stale_upload', 'Stale pending upload')], max_length=24)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], db_index=True, default='pending', max_length=16)),
                ('requested_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('next_attempt_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_error', models.TextField(blank=True)),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_blob_deletions', to='api.deal')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_document_blob_deletions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['requested_at', 'id'],
                'indexes': [models.Index(fields=['status', 'next_attempt_at'], name='doc_blob_del_status_next_idx')],
            },
        ),
    ]
